Epoch: [32m  0/200[39m [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[39m • Time Elapsed: [33m0:00:00[39m • Time Remaining: [36m-:--:--
Train Loss: [1m1.9973[22m • Validation Loss: [1m1.7014[22m • Validation Accuracy: [1m37.27[22m% • Learning Rate: [1m0.00700[22m • Sparsity: [1m0.0[22m%
Best Validation Loss: 1.7014, achive at epoch 1 with 0.0% sparsity































  File "/global/home/users/njo/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/global/home/users/njo/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/global/home/users/njo/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/global/home/users/njo/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Epoch: [32m114/200[39m [91m━━━━━━━━━━━━━━━━━━━━━━╸[90m━━━━━━━━━━━━━━━━━[39m • Time Elapsed: [33m0:21:59[39m • Time Remaining: [36m0:15:36
Train Loss: [1m0.0430[22m • Validation Loss: [1m0.3998[22m • Validation Accuracy: [1m91.68[22m% • Learning Rate: [1m0.00700[22m • Sparsity: [1m0.0[22m%
Best Validation Loss: 0.3044, achive at epoch 33 with 0.0% sparsity
Best Validation Accuracy: 92.37%, achive at epoch 112 with 0.0% sparsity
[?25hTraceback (most recent call last):
Traceback (most recent call last):
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/queues.py", line 245, in _feed
    send_bytes(obj)
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/queues.py", line 245, in _feed
    send_bytes(obj)
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/global/home/users/njo/anaconda3/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
Traceback (most recent call last):
  File "./python/train_CIFAR_new.py", line 417, in <module>
    main()
  File "./python/train_CIFAR_new.py", line 335, in main
    avg_train_loss = train_one_epoch(model, trainloader, optimizer, criterion, scheduler, args.grad_clip)
  File "./python/train_CIFAR_new.py", line 101, in train_one_epoch
    running_loss += loss.item()
KeyboardInterrupt