2023-12-22 13:39:00,274 INFO    MainThread:4109 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2023-12-22 13:39:00,275 INFO    MainThread:4109 [wandb_setup.py:_flush():76] Configure stats pid to 4109
2023-12-22 13:39:00,275 INFO    MainThread:4109 [wandb_setup.py:_flush():76] Loading settings from /global/home/users/njo/.config/wandb/settings
2023-12-22 13:39:00,275 INFO    MainThread:4109 [wandb_setup.py:_flush():76] Loading settings from /global/home/users/njo/PAdam/wandb/settings
2023-12-22 13:39:00,275 INFO    MainThread:4109 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-22 13:39:00,275 INFO    MainThread:4109 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-22 13:39:00,275 INFO    MainThread:4109 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'python/train_CIFAR.py', 'program_abspath': '/global/home/users/njo/PAdam/python/train_CIFAR.py', 'program': './python/train_CIFAR.py'}
2023-12-22 13:39:00,275 INFO    MainThread:4109 [wandb_init.py:_log_setup():524] Logging user logs to /global/home/users/njo/PAdam/wandb/run-20231222_133900-qg3ap2dx/logs/debug.log
2023-12-22 13:39:00,275 INFO    MainThread:4109 [wandb_init.py:_log_setup():525] Logging internal logs to /global/home/users/njo/PAdam/wandb/run-20231222_133900-qg3ap2dx/logs/debug-internal.log
2023-12-22 13:39:00,275 INFO    MainThread:4109 [wandb_init.py:init():564] calling init triggers
2023-12-22 13:39:00,275 INFO    MainThread:4109 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'script_dir': '/global/home/users/njo/PAdam/python', 'relative_paths': True, 'data_dir': '../data/CIFAR10', 'out_dir': './CIFAR10/tests', 'save_checkpoints': True, 'wandb_log': True, 'wandb_project': 'PAdam', 'wandb_run_name': 'ResNet181703281132.2646532', 'num_workers': 4, 'batch_size': 400, 'epochs': 100, 'optimizer_name': 'AdamW', 'max_lr': 0.005, 'lambda_p': 5e-05, 'p_norm': 0.8, 'beta1': 0.9, 'beta2': 0.999, 'grad_clip': 1.0, 'decay_lr': True, 'lr1': False, 'warmup_iters': 500, 'lr_decay_frac': 1.0, 'min_lr': 1e-05, 'small_weights_threshold': 1e-13, 'backend': 'nccl', 'device': 'cuda:3', 'dtype': 'bfloat16', 'compile': True}
2023-12-22 13:39:00,275 INFO    MainThread:4109 [wandb_init.py:init():614] starting backend
2023-12-22 13:39:00,275 INFO    MainThread:4109 [wandb_init.py:init():618] setting up manager
2023-12-22 13:39:00,276 INFO    MainThread:4109 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-12-22 13:39:00,278 INFO    MainThread:4109 [wandb_init.py:init():624] backend started and connected
2023-12-22 13:39:00,282 INFO    MainThread:4109 [wandb_init.py:init():716] updated telemetry
2023-12-22 13:39:00,321 INFO    MainThread:4109 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-12-22 13:39:00,700 INFO    MainThread:4109 [wandb_run.py:_on_init():2254] communicating current version
2023-12-22 13:39:00,768 INFO    MainThread:4109 [wandb_run.py:_on_init():2263] got version response 
2023-12-22 13:39:00,768 INFO    MainThread:4109 [wandb_init.py:init():800] starting run threads in backend
2023-12-22 13:39:01,256 WARNING MainThread:4109 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "/global/home/users/njo/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/global/home/users/njo/anaconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 811, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/global/home/users/njo/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/global/home/users/njo/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/global/home/users/njo/anaconda3/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/global/home/users/njo/anaconda3/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/global/home/users/njo/anaconda3/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-12-22 13:39:09,887 WARNING MsgRouterThr:4109 [router.py:message_loop():77] message_loop has been closed
